#ifndef PINYINSEARCH_GLOBAL_H
#define PINYINSEARCH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PINYINSEARCH_LIBRARY)
#  define PINYINSEARCHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PINYINSEARCHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PINYINSEARCH_GLOBAL_H
